[package]
name = "riggs-shell"
version.workspace = true
edition.workspace = true

[dependencies]
riggs-types = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
ed25519-dalek = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
portable-pty = { workspace = true }
